import qrcode from 'qrcode-generator';
import { useMemo } from 'react';

/**
 * FR-008 — the QR code is drawn right in the browser. The otpauth:// string contains the secret key so it is never sent
 * to an outside QR service. The SVG is generated by the library from the backend's string (it has its own white
 * background / black dots so apps can scan it).
 */
const QrCode = ({ value, label }: { value: string; label: string }) => {
  const svg = useMemo(() => {
    const qr = qrcode(0, 'M');
    qr.addData(value);
    qr.make();
    return qr.createSvgTag({ cellSize: 4, margin: 0, scalable: true });
  }, [value]);

  return (
    <div
      role="img"
      aria-label={label}
      className="border-line-strong bg-surface-raised box-border size-45 flex-none rounded-sm border-[1.5px] p-3 [&_svg]:block [&_svg]:size-full"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
};

export default QrCode;
