import type { ApiResponse } from '@/types/api.types';
import type { UserType } from '@/types/user.types';
import type {
  AuthResultType,
  AuthorizeUrlType,
  ChangePasswordInput,
  LoginInput,
  LoginResultType,
  MfaVerifyInput,
  RegisterInput,
  ResetPasswordInput,
  ResetTokenType,
  SetPasswordInput,
  UpdateProfileInput,
  SocialProvider,
} from '@/types/auth.types';
import { privateApi, publicApi } from '@/utils/axiosInstance';

class AuthApi {
  /** Returns the shared response as is { success, message, data } to show the backend's message exactly. */
  static login = async (input: LoginInput) => {
    const response = await publicApi.post<ApiResponse<LoginResultType>>('/auth/login', input);
    return response.data;
  };

  /**
   * FR-008: step 2 of admin sign-in; a correct code makes the backend issue accessToken + refresh cookie like a normal
   * login.
   */
  static verifyMfa = async (input: MfaVerifyInput) => {
    const response = await publicApi.post<ApiResponse<AuthResultType>>('/auth/mfa/verify', input);
    return response.data;
  };

  /**
   * FR-001. Returns the shared response as is; on success the backend signs in right away (accessToken + refresh
   * cookie).
   */
  static register = async (input: RegisterInput) => {
    const response = await publicApi.post<ApiResponse<AuthResultType>>('/auth/register', input);
    return response.data;
  };

  /**
   * The URL of the Google sign-in page (client_id, redirect_uri come from the backend); `state` is generated by the FE
   * to prevent CSRF.
   */
  static googleAuthorizeUrl = async (state: string) => {
    const response = await publicApi.get<ApiResponse<AuthorizeUrlType>>('/auth/google/authorize-url', {
      params: { state },
    });
    return response.data;
  };

  /** `code` is the authorization code that Google returns to the frontend's redirect_uri. */
  static loginWithSocial = async (provider: SocialProvider, code: string) => {
    const response = await publicApi.post<ApiResponse<LoginResultType>>(`/auth/${provider}`, { code });
    return response.data;
  };

  /** FR-007: always returns the same message whether or not the email exists. */
  static verifyResetToken = async (token: string) => {
    const response = await publicApi.post<ApiResponse<ResetTokenType>>('/auth/reset-password/verify', { token });
    return response.data;
  };

  static resetPassword = async (input: ResetPasswordInput) => {
    const response = await publicApi.post<ApiResponse<null>>('/auth/reset-password', input);
    return response.data;
  };

  static forgotPassword = async (email: string) => {
    const response = await publicApi.post<ApiResponse<null>>('/auth/forgot-password', { email });
    return response.data;
  };

  /** Set a password for the first time for an account created through Google (needs sign-in). */
  static setPassword = async (input: SetPasswordInput) => {
    const response = await privateApi.post<ApiResponse<null>>('/auth/set-password', input);
    return response.data;
  };

  /** The refresh token lives in an HttpOnly cookie, not sent through the body. */
  static refreshToken = async () => {
    const response = await publicApi.post<ApiResponse<AuthResultType>>('/auth/refresh');
    return response.data.data;
  };

  /** The profile of the signed-in user themself (Account page). */
  static getMe = async () => {
    const response = await privateApi.get<ApiResponse<UserType>>('/auth/me');
    return response.data;
  };

  /** Edit full name, phone number, address; the email cannot be changed. */
  static updateMe = async (input: UpdateProfileInput) => {
    const response = await privateApi.put<ApiResponse<UserType>>('/auth/me', input);
    return response.data;
  };

  /** An already-cropped avatar (square JPEG); the backend re-checks and stores it as a JPEG of at most 512px. */
  static uploadAvatar = async (photo: Blob) => {
    const form = new FormData();
    form.append('file', photo, 'avatar.jpg');
    const response = await privateApi.put<ApiResponse<UserType>>('/auth/me/avatar', form, {
      headers: { 'Content-Type': 'multipart/form-data' },
      timeout: 30000,
    });
    return response.data;
  };

  static removeAvatar = async () => {
    const response = await privateApi.delete<ApiResponse<UserType>>('/auth/me/avatar');
    return response.data;
  };

  /** Change password; on success the backend signs out every device (including this session). */
  static changePassword = async (input: ChangePasswordInput) => {
    const response = await privateApi.post<ApiResponse<null>>('/auth/change-password', input);
    return response.data;
  };

  static logout = async () => {
    const response = await privateApi.post<ApiResponse<null>>('/auth/logout');
    return response.data;
  };
}
export default AuthApi;
