package com.techx.intervue.modules.farmer.services.impl;

import com.techx.intervue.modules.farmer.entities.FarmerApplicationHistory;
import com.techx.intervue.modules.farmer.entities.FarmerProfile;
import com.techx.intervue.modules.farmer.enums.ApprovalStatus;
import com.techx.intervue.modules.farmer.exceptions.FarmerApplicationExistsException;
import com.techx.intervue.modules.farmer.exceptions.FarmerProfileNotFoundException;
import com.techx.intervue.modules.farmer.exceptions.InvalidApprovalTransitionException;
import com.techx.intervue.modules.farmer.repositories.FarmerApplicationHistoryRepository;
import com.techx.intervue.modules.farmer.repositories.FarmerProfileRepository;
import com.techx.intervue.modules.farmer.requests.FarmerApplicationRequest;
import com.techx.intervue.modules.farmer.requests.RejectFarmerRequest;
import com.techx.intervue.modules.farmer.requests.SuspendFarmerRequest;
import com.techx.intervue.modules.farmer.resources.AdminFarmerDetailResource;
import com.techx.intervue.modules.farmer.resources.AdminFarmerListItemResource;
import com.techx.intervue.modules.farmer.resources.FarmerApplicationHistoryResource;
import com.techx.intervue.modules.farmer.resources.FarmerProfileResource;
import com.techx.intervue.modules.farmer.services.interfaces.FarmerServiceInterface;
import com.techx.intervue.modules.notification.enums.NotificationKind;
import com.techx.intervue.modules.notification.resources.NotificationEvent;
import com.techx.intervue.modules.notification.services.interfaces.NotificationServiceInterface;
import com.techx.intervue.modules.user.entities.User;
import com.techx.intervue.modules.user.enums.RoleType;
import com.techx.intervue.modules.user.exceptions.InvalidFieldException;
import com.techx.intervue.modules.user.repositories.UserRepository;
import com.techx.intervue.modules.user.services.impl.UserSessionCache;
import com.techx.intervue.resources.PageResource;
import java.time.Duration;
import java.time.Instant;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import lombok.AllArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

/**
 * Backend roadmap step 3 (docs/MarketLink-Farmer-Profile-and-Approval.md), extended per the
 * prototype (docs/prototype/customer/become-farmer.html). Role-transition model: an account has
 * only one role at a time (D-08 — no multi-profile). A Customer who applies keeps the customer role
 * until an Admin approves, and only then switches to farmer (§4, §7).
 *
 * <p>The application only contains stall information, images/videos and the commitments. The
 * products, farming method and markets they want to sell at are declared after approval in the
 * Farmer panel (FR-060…FR-064), so they are not in the application.
 *
 * <p>Images/videos store a local path generated by {@code FarmerUploadService} — for test/demo
 * only, not production storage infrastructure.
 */
@Service
@AllArgsConstructor
public class FarmerService implements FarmerServiceInterface {

    private static final String LIST_SEPARATOR = ";";

    /**
     * A freshly uploaded image that has not yet been sent with an application is not garbage — only
     * clean up files older than this mark.
     */
    private static final Duration KEEP_FRESH_UPLOADS_FOR = Duration.ofHours(1);

    private final FarmerProfileRepository farmerProfileRepository;
    private final FarmerApplicationHistoryRepository historyRepository;
    private final FarmerUploadService uploadService;
    private final UserRepository userRepository;
    private final UserSessionCache userSessionCache;
    private final NotificationServiceInterface notifications;

    /**
     * §4: create a PENDING profile, does not accept approval_status from the client.
     *
     * <p>A rejected applicant may re-apply: the old profile is overwritten (rejected → pending,
     * reason cleared) to keep UNIQUE(user_id), while the previous submission's content and reason
     * stay intact in farmer_application_history. Pending, approved or suspended applicants cannot
     * apply again.
     */
    @Override
    @Transactional
    public FarmerProfileResource apply(Long userId, FarmerApplicationRequest request) {
        FarmerProfile profile =
                farmerProfileRepository.findByUserId(userId).orElseGet(FarmerProfile::new);
        if (profile.getId() != null && profile.getApprovalStatus() != ApprovalStatus.REJECTED) {
            throw new FarmerApplicationExistsException();
        }

        assertOwnsFiles(userId, request);

        profile.setUserId(userId);
        profile.setStallName(request.stallName().trim());
        profile.setContactPerson(request.contactPerson().trim());
        profile.setDescription(normalize(request.description()));
        profile.setPhotoPaths(joinList(request.photoUrls()));
        profile.setVideoPath(normalize(request.videoUrl()));
        profile.setApprovalStatus(ApprovalStatus.PENDING);
        profile.setRejectReason(null);
        profile.setApprovedBy(null);
        profile.setApprovedAt(null);
        farmerProfileRepository.save(profile);

        historyRepository.save(
                FarmerApplicationHistory.builder()
                        .userId(userId)
                        .attempt((int) historyRepository.countByUserId(userId) + 1)
                        .stallName(profile.getStallName())
                        .contactPerson(profile.getContactPerson())
                        .description(profile.getDescription())
                        .photoPaths(profile.getPhotoPaths())
                        .videoPath(profile.getVideoPath())
                        .status(ApprovalStatus.PENDING)
                        .build());

        // On re-apply the previous submission's images are no longer referenced by anyone: clean
        // them up right away instead of waiting for the job.
        cleanUpFiles(userId);
        notifications.notifyAdmins(
                NotificationEvent.of(
                        NotificationKind.FARMER_APPLICATION,
                        "/admin/farmers/" + profile.getId(),
                        Map.of("stall", profile.getStallName())));
        return toOwnResource(profile, historyOf(userId));
    }

    /**
     * Withdraw the application while it is still pending: the profile and that submission
     * disappear, and the account goes back to never having applied. Approved, rejected or suspended
     * ones cannot be withdrawn — those states are outcomes that already exist, not pending work.
     */
    @Override
    @Transactional
    public void withdraw(Long userId) {
        FarmerProfile profile =
                farmerProfileRepository
                        .findByUserId(userId)
                        .orElseThrow(FarmerProfileNotFoundException::new);
        if (profile.getApprovalStatus() != ApprovalStatus.PENDING) {
            throw new InvalidApprovalTransitionException(
                    "Only an application that is still waiting can be withdrawn.");
        }
        historyRepository
                .findFirstByUserIdOrderByAttemptDesc(userId)
                .filter(attempt -> attempt.getStatus() == ApprovalStatus.PENDING)
                .ifPresent(historyRepository::delete);
        farmerProfileRepository.delete(profile);
        cleanUpFiles(userId);
    }

    /** The attached images/videos must be files that this same account just uploaded. */
    private void assertOwnsFiles(Long userId, FarmerApplicationRequest request) {
        List<String> urls = request.photoUrls() == null ? List.of() : request.photoUrls();
        for (String url : urls) {
            if (!uploadService.isOwnedBy(url, userId)) {
                throw new InvalidFieldException("photoUrls", "Upload the photos again.");
            }
        }
        if (!uploadService.isOwnedBy(request.videoUrl(), userId)) {
            throw new InvalidFieldException("videoUrl", "Upload the video again.");
        }
    }

    /**
     * Delete this account's files that no application — current or historical — still points to.
     */
    private void cleanUpFiles(Long userId) {
        Set<String> keep = new HashSet<>();
        farmerProfileRepository
                .findByUserId(userId)
                .ifPresent(
                        profile -> {
                            keep.addAll(splitList(profile.getPhotoPaths()));
                            if (profile.getVideoPath() != null) {
                                keep.add(profile.getVideoPath());
                            }
                        });
        for (FarmerApplicationHistory attempt :
                historyRepository.findByUserIdOrderByAttemptDesc(userId)) {
            keep.addAll(splitList(attempt.getPhotoPaths()));
            if (attempt.getVideoPath() != null) {
                keep.add(attempt.getVideoPath());
            }
        }
        uploadService.deleteUnreferenced(userId, keep, Instant.now().minus(KEEP_FRESH_UPLOADS_FOR));
    }

    /**
     * §5.1: null if the account never applied — the FE treats this as the "empty" state, not an
     * error.
     */
    @Override
    public FarmerProfileResource getMyProfile(Long userId) {
        return farmerProfileRepository
                .findByUserId(userId)
                .map(profile -> toOwnResource(profile, historyOf(userId)))
                .orElse(null);
    }

    /**
     * §6.1: pagination, filter by approval status, search by stall name / contact person / email /
     * phone. The sort order is in the JPQL statement so the Pageable here carries no Sort.
     */
    @Override
    public PageResource<AdminFarmerListItemResource> listForAdmin(
            ApprovalStatus status, String query, int page, int pageSize) {
        String like =
                StringUtils.hasText(query)
                        ? "%" + query.trim().toLowerCase(Locale.ROOT) + "%"
                        : null;
        Pageable pageable = PageRequest.of(Math.max(page - 1, 0), pageSize);
        Page<AdminFarmerListItemResource> result =
                farmerProfileRepository.search(status, like, pageable);
        return PageResource.<AdminFarmerListItemResource>builder()
                .items(result.getContent())
                .page(page)
                .pageSize(pageSize)
                .total(result.getTotalElements())
                .build();
    }

    /** §6.2. */
    @Override
    public AdminFarmerDetailResource getDetailForAdmin(Long farmerId) {
        FarmerProfile profile = findProfileOrThrow(farmerId);
        return toDetailResource(profile, findOwnerOrThrow(profile));
    }

    /** §7: only PENDING can be approved; the role switches to farmer in the same transaction. */
    @Override
    @Transactional
    public AdminFarmerDetailResource approve(Long farmerId, Long adminUserId) {
        FarmerProfile profile = findProfileOrThrow(farmerId);
        if (profile.getApprovalStatus() != ApprovalStatus.PENDING) {
            throw new InvalidApprovalTransitionException(
                    "Only a pending application can be approved.");
        }
        Instant now = Instant.now();
        profile.setApprovalStatus(ApprovalStatus.APPROVED);
        profile.setApprovedBy(adminUserId);
        profile.setApprovedAt(now);
        farmerProfileRepository.save(profile);
        decideLatestAttempt(profile.getUserId(), ApprovalStatus.APPROVED, null, adminUserId, now);

        User owner = findOwnerOrThrow(profile);
        owner.setRole(RoleType.FARMER);
        userRepository.save(owner);
        // JwtAuthFilter reads the role from the session in Redis, not from the claim: without
        // writing it back, a Farmer
        // who was just approved would still carry ROLE_CUSTOMER until the access token TTL ends.
        userSessionCache.updateRoles(owner.getId(), Set.of(RoleType.FARMER));

        tellOwner(profile, NotificationKind.FARMER_APPROVED, "/farmer", Map.of());
        return toDetailResource(profile, owner);
    }

    /**
     * docs/prototype/admin/farmers.html — only PENDING can be rejected; the role stays customer (it
     * never switched to farmer).
     */
    @Override
    @Transactional
    public AdminFarmerDetailResource reject(
            Long farmerId, RejectFarmerRequest request, Long adminUserId) {
        FarmerProfile profile = findProfileOrThrow(farmerId);
        if (profile.getApprovalStatus() != ApprovalStatus.PENDING) {
            throw new InvalidApprovalTransitionException(
                    "Only a pending application can be rejected.");
        }
        String reason = request.reason().trim();
        profile.setApprovalStatus(ApprovalStatus.REJECTED);
        profile.setRejectReason(reason);
        farmerProfileRepository.save(profile);
        decideLatestAttempt(
                profile.getUserId(), ApprovalStatus.REJECTED, reason, adminUserId, Instant.now());
        tellOwner(
                profile,
                NotificationKind.FARMER_REJECTED,
                "/become-farmer",
                Map.of("reason", reason));
        return toDetailResource(profile, findOwnerOrThrow(profile));
    }

    /**
     * The Admin's result is written to the latest submission. If no row is found (the profile
     * predates the history table and the migration missed it), skip — a missing history must not
     * block the approval.
     */
    private void decideLatestAttempt(
            Long userId, ApprovalStatus status, String reason, Long adminUserId, Instant at) {
        historyRepository
                .findFirstByUserIdOrderByAttemptDesc(userId)
                .ifPresent(
                        attempt -> {
                            attempt.setStatus(status);
                            attempt.setRejectReason(reason);
                            attempt.setDecidedBy(adminUserId);
                            attempt.setDecidedAt(at);
                            historyRepository.save(attempt);
                        });
    }

    /**
     * §8: only APPROVED can be suspended; the role stays farmer (D-09 — can still sign in). The
     * reason is required because the Farmer reads it back on their own profile page.
     */
    @Override
    @Transactional
    public AdminFarmerDetailResource suspend(
            Long farmerId, SuspendFarmerRequest request, Long adminUserId) {
        FarmerProfile profile = findProfileOrThrow(farmerId);
        if (profile.getApprovalStatus() != ApprovalStatus.APPROVED) {
            throw new InvalidApprovalTransitionException(
                    "Only an approved farmer can be suspended.");
        }
        profile.setApprovalStatus(ApprovalStatus.SUSPENDED);
        profile.setSuspendReason(request.reason().trim());
        profile.setSuspendedBy(adminUserId);
        profile.setSuspendedAt(Instant.now());
        farmerProfileRepository.save(profile);
        tellOwner(profile, NotificationKind.FARMER_SUSPENDED, "/farmer/pending", Map.of());
        return toDetailResource(profile, findOwnerOrThrow(profile));
    }

    /**
     * docs/prototype/admin/farmers.html "Reinstate" — only SUSPENDED goes back to APPROVED; the
     * role has been farmer since approve, suspend does not change the role so there is nothing to
     * change back here.
     */
    @Override
    @Transactional
    public AdminFarmerDetailResource reinstate(Long farmerId) {
        FarmerProfile profile = findProfileOrThrow(farmerId);
        if (profile.getApprovalStatus() != ApprovalStatus.SUSPENDED) {
            throw new InvalidApprovalTransitionException(
                    "Only a suspended farmer can be reinstated.");
        }
        profile.setApprovalStatus(ApprovalStatus.APPROVED);
        // Once a suspension is lifted the old reason is no longer true: the Farmer should not see
        // the red banner from the
        // last time.
        profile.setSuspendReason(null);
        profile.setSuspendedBy(null);
        profile.setSuspendedAt(null);
        farmerProfileRepository.save(profile);
        tellOwner(profile, NotificationKind.FARMER_REINSTATED, "/farmer", Map.of());
        return toDetailResource(profile, findOwnerOrThrow(profile));
    }

    /**
     * FR-042: notify the order owner; push in realtime after commit (NotificationService uses
     * afterCommit).
     */
    private void tellOwner(
            FarmerProfile profile, NotificationKind kind, String link, Map<String, String> extra) {
        Map<String, String> params = new HashMap<>(extra);
        params.put("stall", profile.getStallName());
        notifications.dispatch(
                List.of(profile.getUserId()), NotificationEvent.of(kind, link, params));
    }

    private FarmerProfile findProfileOrThrow(Long farmerId) {
        return farmerProfileRepository
                .findById(farmerId)
                .orElseThrow(FarmerProfileNotFoundException::new);
    }

    private User findOwnerOrThrow(FarmerProfile profile) {
        return userRepository
                .findById(profile.getUserId())
                .orElseThrow(() -> new BadCredentialsException("Account not found."));
    }

    /** An account's application history, newest first. */
    private List<FarmerApplicationHistoryResource> historyOf(Long userId) {
        return historyRepository.findByUserIdOrderByAttemptDesc(userId).stream()
                .map(FarmerService::toHistoryResource)
                .toList();
    }

    private static FarmerApplicationHistoryResource toHistoryResource(
            FarmerApplicationHistory attempt) {
        return FarmerApplicationHistoryResource.builder()
                .id(attempt.getId())
                .attempt(attempt.getAttempt())
                .stallName(attempt.getStallName())
                .contactPerson(attempt.getContactPerson())
                .description(attempt.getDescription())
                .photoUrls(splitList(attempt.getPhotoPaths()))
                .videoUrl(attempt.getVideoPath())
                .status(attempt.getStatus())
                .rejectReason(attempt.getRejectReason())
                .decidedAt(attempt.getDecidedAt())
                .submittedAt(attempt.getSubmittedAt())
                .build();
    }

    private AdminFarmerDetailResource toDetailResource(FarmerProfile profile, User owner) {
        return AdminFarmerDetailResource.builder()
                .id(profile.getId())
                .userId(owner.getId())
                .stallName(profile.getStallName())
                .contactPerson(profile.getContactPerson())
                .description(profile.getDescription())
                .photoUrls(splitList(profile.getPhotoPaths()))
                .videoUrl(profile.getVideoPath())
                .email(owner.getEmail())
                .phone(owner.getPhone())
                .address(owner.getAddress())
                .approvalStatus(profile.getApprovalStatus())
                .rejectReason(profile.getRejectReason())
                .suspendReason(profile.getSuspendReason())
                .approvedAt(profile.getApprovedAt())
                .suspendedAt(profile.getSuspendedAt())
                .createdAt(profile.getCreatedAt())
                .history(historyOf(profile.getUserId()))
                .customerSince(owner.getCreatedAt())
                .accountStatus(owner.getStatus())
                .build();
    }

    private static FarmerProfileResource toOwnResource(
            FarmerProfile profile, List<FarmerApplicationHistoryResource> history) {
        return FarmerProfileResource.builder()
                .id(profile.getId())
                .stallName(profile.getStallName())
                .contactPerson(profile.getContactPerson())
                .description(profile.getDescription())
                .photoUrls(splitList(profile.getPhotoPaths()))
                .videoUrl(profile.getVideoPath())
                .approvalStatus(profile.getApprovalStatus())
                .rejectReason(profile.getRejectReason())
                .suspendReason(profile.getSuspendReason())
                .history(history)
                .createdAt(profile.getCreatedAt())
                .build();
    }

    /** Optional text field — an empty/whitespace-only string is stored as NULL, not as garbage. */
    private static String normalize(String value) {
        return StringUtils.hasText(value) ? value.trim() : null;
    }

    private static String joinList(List<String> values) {
        if (values == null || values.isEmpty()) {
            return null;
        }
        String joined =
                values.stream()
                        .filter(StringUtils::hasText)
                        .map(String::trim)
                        .reduce((a, b) -> a + LIST_SEPARATOR + b)
                        .orElse(null);
        return StringUtils.hasText(joined) ? joined : null;
    }

    private static List<String> splitList(String stored) {
        if (!StringUtils.hasText(stored)) {
            return Collections.emptyList();
        }
        return List.of(stored.split(LIST_SEPARATOR));
    }
}
